[general]
import = ["~/.config/alacritty/dracula.toml"]

[env]
TERM = "alacritty"

[cursor.style]
shape = "Block"
blinking = "Off"

[font]
size = 10.0

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh://|ftp://)[^\u0000-\u001f<>\"\\s{-}\\^`]+"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85

[window.dimensions]
columns = 130
lines = 42

[window.padding]
x = 4
y = 4
