[general]
live_config_reload = true

[colors]

[colors.bright]
black = "#44475a"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[cursor.style]
shape = "Block"
blinking = "Off"

[cursor]
unfocused_hollow = true

[font]
size = 9.0

[font.bold]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[font.italic]
family = "MesloLGSDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 130
lines = 42

[window.padding]
x = 2
y = 2
