[env]
TERM = "alacritty"

[colors]

[colors.bright]
black = "#44475a"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#e6e6e6"
yellow = "#ffffa5"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.selection]
background = "#44475a"
text = "#f8f8f2"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Off"

[font]
size = 10.0

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 130
lines = 42

[window.padding]
x = 4
y = 4
