#!/usr/bin/env bash
set -euo pipefail

branch_symbol=""

__parse_git_branch() {
	branch=$(git symbolic-ref HEAD 2>/dev/null) || true
	if [[ -z $branch ]]; then
		branch=":$(git rev-parse --short HEAD 2>/dev/null)" || return
	fi
	branch=${branch##*/}
	echo -n "${branch_symbol} ${branch} ($(git rev-parse --short HEAD))"
}

tmux_path=$(tmux display -p "#{pane_current_path}")
cd "$tmux_path" || exit
branch=""
if [ -n "${git_branch=$(__parse_git_branch)}" ]; then
	branch="$git_branch"
fi

if [ -n "$branch" ]; then
	echo "${branch} "
fi
