#!/usr/bin/env bash
set -euo pipefail

wan_ip=""
lan_ip=""
tmp_file="${XDG_RUNTIME_DIR:-/tmp}/tmux-ip-${UID}.txt"

getLanIP() {
	mapfile -t all_nics < <(ip addr show | cut -d ' ' -f2 | tr -d : | grep -v '^lo$' | grep .)
	for nic in "${all_nics[@]}"; do
		lan_ip="$(ip addr show "${nic}" | grep '\<inet\>' | tr -s ' ' | cut -d ' ' -f3)" || true
		lan_ip="${lan_ip%/*}"
		lan_ip="$(echo "$lan_ip" | tail -1)"
		[ -n "$lan_ip" ] && break
	done
}

getWanIP() {
	if [ -f "$tmp_file" ]; then
		last_update=$(stat -c "%Y" "${tmp_file}")
		time_now=$(date +%s)
		update_period=900
		if [ $((time_now - last_update)) -lt $update_period ]; then
			wan_ip=$(cat "${tmp_file}")
		fi
	fi

	if [ -z "$wan_ip" ]; then
		if wan_ip=$(curl --max-time 2 -s https://whatismyip.akamai.com/); then
			echo "${wan_ip}" >"$tmp_file"
		elif [ -f "${tmp_file}" ]; then
			wan_ip=$(cat "$tmp_file")
		fi
	fi
}

getLanIP
getWanIP

echo "${wan_ip} / ${lan_ip-N/a}"
