#!/usr/bin/env bash
set -euo pipefail

mod_symbol="~"

__parse_git_stats() {
	if ! type git >/dev/null 2>&1; then
		return
	fi
	if [[ -z $(git rev-parse --git-dir 2>/dev/null) ]]; then return; fi
	modified=$(git ls-files --modified | wc -l)
	echo "$modified"
}

tmux_path=$(tmux display -p "#{pane_current_path}")
cd "$tmux_path" || exit
stats=""
if [ -n "${git_stats=$(__parse_git_stats)}" ]; then
	stats="$git_stats"
fi
if [[ -n "$stats" && $stats -gt 0 ]]; then
	echo "${mod_symbol}${stats} "
fi
