#!/usr/bin/env bash
set -euo pipefail

staged_symbol="⊕ "

__parse_git_stats() {
	if [[ -z $(git rev-parse --git-dir 2>/dev/null) ]]; then return; fi
	staged=$(git diff --staged --name-status | wc -l)
	echo "$staged"
}

tmux_path=$(tmux display -p "#{pane_current_path}")
cd "$tmux_path" || exit

stats=""
if [ -n "${git_stats=$(__parse_git_stats)}" ]; then
	stats="$git_stats"
fi
if [[ -n "$stats" && $stats -gt 0 ]]; then
	stats="${stats#"${stats%%[![:space:]]*}"}"
	echo "${staged_symbol}${stats} "
fi
