#!/usr/bin/env bash

staged_symbol=" "

__parse_git_stats() {
	if ! type git >/dev/null 2>&1; then
		return
	fi
	[[ -z $(git stash list 2>/dev/null) ]] && return
	stashed=$(git stash list | wc -l)
	echo "$stashed"
}

tmux_path=$(tmux display -p "#{pane_current_path}")
cd "$tmux_path" || exit

stats=""
if [ -n "${git_stats=$(__parse_git_stats)}" ]; then
	stats="$git_stats"
fi
if [[ -n "$stats" && $stats -gt 0 ]]; then
	stats="${stats#"${stats%%[![:space:]]*}"}"
	echo "${staged_symbol}${stats} "
fi
