[files]
extend-exclude = [
    "icons/",
    "ranger/",
    "nvim/lazy-lock.json",
    "nvim/lua/plugins/editing.lua",
    "gdb/",
]

[default.extend-words]
crypted = "crypted"
grup = "grup"
yot = "yot"
ot = "ot"
als = "als"
frmat = "frmat"
