color_theme = "dracula"
theme_background = false
vim_keys = true
terminal_sync = true
proc_filter_kernel = true
show_cpu_watts = true
freq_mode = "average"
clock_format = "%X"
save_config_on_exit = false
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
