call plug#begin('~/.vim/bundle')

function! BuildYCM(info)
    if a:info.status == 'installed' || a:info.force
        !python3 ./install.py --clangd-completer --clang-completer --go-completer --rust-completer --ts-completer
    endif
endfunction

Plug 'Julian/vim-textobj-variable-segment'
Plug 'LnL7/vim-nix', { 'for': 'nix' }
Plug 'SirVer/ultisnips'
Plug 'Valloric/YouCompleteMe', { 'do': function('BuildYCM') }
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dag/vim-fish', { 'for': 'fish' }
Plug 'easymotion/vim-easymotion'
Plug 'edkolev/tmuxline.vim'
Plug 'fatih/vim-go', { 'for': 'go', 'do': ':GoInstallBinaries' }
Plug 'glts/vim-textobj-comment'
Plug 'godlygeek/tabular'
Plug 'hashivim/vim-terraform', { 'for': 'tf' }
Plug 'honza/vim-snippets'
Plug 'jiangmiao/auto-pairs'
Plug 'jremmen/vim-ripgrep', { 'on': 'Rg' }
Plug 'kana/vim-operator-user'
Plug 'kana/vim-textobj-lastpat'
Plug 'kana/vim-textobj-user'
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'neovimhaskell/haskell-vim', { 'for': 'haskell' }
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'pbrisbin/vim-syntax-shakespeare'
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable'}
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'ryanoasis/vim-devicons'
Plug 'saschagrunert/dracula', { 'branch': 'mod' }
Plug 'tommcdo/vim-exchange'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-characterize'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
Plug 'tpope/vim-markdown', { 'for': 'markdown' }
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-scriptease'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-airline/vim-airline'
Plug 'dense-analysis/ale'
Plug 'wellle/targets.vim'
Plug 'zirrostig/vim-schlepp'

call plug#end()
