#!/usr/bin/env bash

# Laptop
if xrandr --listmonitors | grep -q DP-1-2; then
    xrandr --output DP-1-1 --left-of eDP-1
    xrandr --output DP-1-2 --left-of DP-1-1
    i3-msg restart
fi

# Set the wallpaper
feh --bg-scale ~/.dotfiles/wallpaper/blurred.jpg

# Setup default applications
# i3-msg exec "xautolock -time 5 -corners --00 -locker 'i3lock-fancy -p'"
i3-msg exec picom
i3-msg exec dunst
i3-msg exec nm-applet
i3-msg exec unclutter

i3-msg exec "alacritty -e fish -C \"tmux new-session -s work fish -C 'vim +PlugUpgrade +PlugUpdate +qa!'\""
i3-msg exec chromium
i3-msg exec thunderbird
i3-msg exec hexchat
i3-msg exec "ibus-daemon --daemonize --xim"
