#!/usr/bin/env bash

setup-screens

# Setup default applications
i3-msg exec picom
i3-msg exec dunst
i3-msg exec nm-applet
i3-msg exec blueman-applet

i3-msg exec "alacritty -e fish -C \"tmux new-session -s work fish -C 'vim +PlugUpgrade +PlugUpdate +qa!'\""
i3-msg exec "google-chrome-stable --force-device-scale-factor=1.5"
i3-msg exec hexchat
i3-msg exec "ibus-daemon --daemonize --xim"
