#!/usr/bin/env bash

i3-msg exec setup-screens

# Setup default applications
i3-msg exec picom
i3-msg exec dunst
i3-msg exec nm-applet
i3-msg exec blueman-applet

i3-msg exec "alacritty -e fish -C \"tmux new-session -s work\""
i3-msg exec "google-chrome-stable --force-device-scale-factor=1.5"
