{ config, lib, pkgs, nixpkgs, ... }:
{
  imports = [
    "${nixpkgs}/nixos/modules/installer/scan/not-detected.nix"
  ];

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      max-jobs = lib.mkDefault 8;
      trusted-users = [ "root" "sascha" ];
    };
  };

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    (import ./setup-screens.nix { inherit writeShellScriptBin; })
    acpilight
    alacritty
    arandr
    arc-theme
    asciinema
    autojump
    bat
    bats
    binutils
    bom
    bpftools
    buf
    buildah
    cachix
    calc
    capnproto
    cargo-edit
    cargo-watch
    cfssl
    clang-tools
    clang_21
    claude-code
    cmake
    cni-plugins
    conmon
    conmon-rs
    conntrack-tools
    cosign
    cri-o
    cri-tools
    criu
    crun
    ctags
    dmenu
    dunst
    eza
    fd
    feh
    file
    fuse-overlayfs
    fzf
    gcc
    gdb
    gh
    ginkgo
    git
    git-lfs
    gnumake
    go_1_26
    gofumpt
    golangci-lint
    google-chrome
    google-cloud-sdk
    gopls
    gotools
    graphviz
    haskellPackages.alex
    heaptrack
    htop
    imagemagick
    inetutils
    iptables
    j4-dmenu-desktop
    jq
    jwt-cli
    kind
    kubectl
    kubernetes
    kustomize
    ldns
    libcgroup
    lima
    lm_sensors
    lshw
    lvm2
    lxappearance
    mediainfo
    nix-index
    nix-prefetch-git
    nixos-shell
    nixpkgs-fmt
    nodePackages.prettier
    nodejs
    openssl
    openvpn
    oras
    pahole
    parallel
    pavucontrol
    peek
    perlPackages.Apprainbarf
    picom
    proselint
    protobuf
    protolint
    pstree
    python3
    python3Packages.autopep8
    python3Packages.isort
    python3Packages.osc
    python3Packages.yapf
    ranger
    ripgrep
    rpm
    runc
    rustup
    shellcheck
    shfmt
    signal-desktop
    skopeo
    slirp4netns
    socat
    sysstat
    tig
    tmux
    typos
    unixtools.netstat
    unzip
    usbutils
    vagrant
    valgrind
    virt-manager
    wget
    xclip
    xev
    xsel
    yamllint
    yq-go
    zoom-us
  ];
}
