alias .. "cd .."
alias ... "cd ../.."
alias .... "cd ../../.."
alias ..... "cd ../../../.."
alias cat "bat"
alias duf "du -sh *"
alias f "fd"
alias ff "fd --type f"
alias g "git"
alias ga "git add"
alias gaa "git add -A"
alias gb "git branch"
alias gba "git branch -a"
alias gbv "git branch -vv"
alias gca "git commit -s --amend"
alias gcan "git commit -s --amend --no-edit"
alias gcaa "git commit -s -a --amend --no-edit"
alias gcl "git clone"
alias gcmsg "git commit -sm"
alias gco "git checkout"
alias gd "git diff"
alias gdc "git diff --cached"
alias glg "git log --stat --max-count=10"
alias glgg "git log --graph --max-count=10"
alias glgga "git log --graph --decorate --all"
alias glo "git log --oneline --decorate --color"
alias glog "git log --oneline --decorate --color --graph"
alias glr "git pull --rebase"
alias gm "git merge"
alias gmn "git merge --no-ff"
alias gp "git push"
alias gpf "git push -f"
alias gr "git reset ."
alias grc "git rebase --continue"
alias grup "git remote update"
alias gupb "gup base"
alias grv "git remote -v"
alias gsp "git stash pop"
alias gss "git stash"
alias gst "git status"
alias h "history"
alias hs "history --search"
alias k "kubectl"
alias kk "kubectl config use-context"
alias l "ls -l"
alias la "ls -a"
alias ll "l -a"
alias llt "ll -T"
alias ls "eza --git -bgF"
alias lt "l -T"
alias m "make"
alias mc "make clean"
alias md "mkdir -p"
alias mm "make -j(nproc)"
alias nup "nix flake update --flake $DOTFILES"
alias p "pwd"
alias po "popd"
alias pu "pushd"
alias r "rm -rf"
alias rup "rustup update"
alias screensleep "xset dpms force off"
alias t "tail -f"
alias ta "tmux attach"
alias tg "cd ~ && tmux"
alias tl "tmux list-sessions"
alias ts "tmux new-session -s"
alias up "rup && sudo nixos-rebuild switch --flake $DOTFILES#nixos && nix develop $DOTFILES --command true && nix-collect-garbage -d"
alias v "nvim"
alias vr "ranger"
alias vv "nvim -u NONE"
