set colorscheme dracula
set draw_borders both
set dirname_in_tabs true
set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$
set tilde_in_titlebar true
set unicode_ellipsis true
set vcs_aware true
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled
set vcs_backend_svn disabled

map dw delete
map ~ set viewmode!
